### ISSUE TITLE
Question: correct way to handle lost session?

### ISSUE THREAD

**Issue by diastremskii** [telegraf/telegraf-flow#6]
Hi. I guess It's not a problem when using some persistent storage, but when using memory session user can "stuck" in a scene after restart of Node.js. 
For example, in a bot with only "start" command and navigation by buttons I tried doing something like this:
```
app.use(Telegraf.memorySession())
app.use(flow.middleware())

app.command('start', ctx => {
  ctx.reply('Hi!')
    .then(() => ctx.flow.enter('main'))
})

app.on('message', ctx => {
  ctx.reply('Bot was restarted! Please try again')
    .then(() => ctx.flow.enter('main'))
})
```

But this way bot sends message about restart for any message not handled inside scene.

Thank you!

**Comment by diastremskii** [comment]
Oh, looks like this works: 
```
flow.command('start', ctx => {
  ctx.reply('Hi!')
    .then(() => ctx.flow.enter('main'))
})

flow.on('message', (ctx, next) => {
  if (!ctx.session._flow) {
    return ctx.reply('Bot was restarted! Please try again')
      .then(() => ctx.flow.enter('main'))
  }
  next()
})

app.use(Telegraf.memorySession())
app.use(flow.middleware())
```

But feels a bit wrong because of accessing "private" property `_flow`. Or this should be considered correct?

**Comment by dotcypress** [comment]
Actually, bot restarting will cause session loss and flow reset(because telegraf-flow use session to store state).

Try this:
```js
app.use(Telegraf.memorySession())

app.command('start', ctx => {
  ctx.reply('Hi!').then(() => ctx.flow.enter('main'))
})

app.use(flow.middleware())

app.on('message', ctx => {
  ctx.reply('Bot was restarted! Please try again').then(() => ctx.flow.enter('main'))
})
```

**Comment by diastremskii** [comment]
Thank you!
