### ISSUE TITLE
Session timeout

### ISSUE THREAD

**Issue by rafaelquines** [telegraf/telegraf-flow#9]
Hi. Congralations by package.
I'd like use a timeout on each flow in my chatbot.

For example, my Wizard Scene has 5 questions. In 3º, the user close telegram. In the other day, he talks with bot, and the flow continue in the same stage.

Do you have some issue or backlog to implement it?

If don't, can I create a pull request?

Thanks

**Comment by dotcypress** [comment]
Hey.

Timeout has been implemented in `telegraf-redis-session`, I think it will fit you requirements.

**Comment by rafaelquines** [comment]
Yes, you're right.

Telegraf-flow must care abour workflow, and session must be responsable by timeout.

Thank you so much
